# Generated by Django 2.2.6 on 2019-11-06 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 11, 22, 47, 107144), verbose_name='date published'),
        ),
    ]
