# Generated by Django 2.2.6 on 2019-11-06 19:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191106_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='fig',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 19, 28, 23, 335429), verbose_name='date published'),
        ),
    ]
