# Generated by Django 2.2.6 on 2019-11-06 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 19, 42, 58, 343754), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='fig',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
