# Generated by Django 2.2.6 on 2019-11-06 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191106_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 6, 49, 82207), verbose_name='date published'),
        ),
    ]
