# Generated by Django 2.2.6 on 2019-11-06 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191106_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 45, 11, 857604), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='fig',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
