# Generated by Django 2.2.6 on 2019-11-06 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191106_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 45, 44, 434039), verbose_name='date published'),
        ),
    ]
