# Generated by Django 2.2.6 on 2019-11-15 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191115_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 7, 28, 13, 788563), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='FriendT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=25)),
                ('Time', models.DateTimeField()),
                ('fdname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdname', to=settings.AUTH_USER_MODEL)),
                ('urname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
