# Generated by Django 2.2.6 on 2019-11-15 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191115_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 9, 5, 20, 433246), verbose_name='date published'),
        ),
    ]
