# Generated by Django 2.2.6 on 2019-11-15 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191115_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendt',
            name='Time',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 9, 33, 15, 841099), verbose_name='date published'),
        ),
    ]
