# Generated by Django 2.2.6 on 2019-11-06 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 40, 11, 443574), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
