# Generated by Django 2.2.6 on 2019-11-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191106_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='Date',
        ),
    ]
