# Generated by Django 2.2.6 on 2019-11-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191115_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='fdname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='friendt',
            name='urname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 9, 52, 36, 19002), verbose_name='date published'),
        ),
    ]
