# Generated by Django 2.2.6 on 2019-11-15 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191115_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 9, 53, 57, 967573), verbose_name='date published'),
        ),
    ]
