# Generated by Django 2.2.6 on 2019-11-15 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 10, 12, 1, 707081), verbose_name='date published'),
        ),
    ]
