# Generated by Django 2.2.6 on 2019-11-15 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191115_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 13, 46, 28, 113276), verbose_name='date published'),
        ),
    ]
