# Generated by Django 2.2.6 on 2019-11-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191115_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 14, 9, 43, 954963), verbose_name='date published'),
        ),
    ]
