# Generated by Django 2.2.6 on 2019-11-15 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20191115_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 41, 48, 482436), verbose_name='date published'),
        ),
    ]
