# Generated by Django 2.2.6 on 2019-11-16 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20191115_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 8, 28, 25, 675963), verbose_name='date published'),
        ),
    ]
