# Generated by Django 2.2.6 on 2019-11-17 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191116_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 16, 16, 0, 464370), verbose_name='date published'),
        ),
    ]
