# Generated by Django 2.2.6 on 2019-11-22 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20191117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='tag',
            field=models.CharField(choices=[('Restaurant', 'R'), ('Cinema', 'C'), ('Travelling', 'T'), ('Others', 'O')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 9, 6, 58, 596209), verbose_name='date published'),
        ),
    ]
