# Generated by Django 2.2.6 on 2019-11-22 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20191122_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 10, 59, 32, 668816), verbose_name='date published'),
        ),
    ]
