# Generated by Django 2.2.6 on 2019-11-22 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20191122_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendt',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 13, 36, 34, 312958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 13, 36, 34, 311361), verbose_name='date published'),
        ),
    ]
