# Generated by Django 2.2.6 on 2019-11-22 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20191122_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 18, 11, 3, 457566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 18, 11, 3, 456101), verbose_name='date published'),
        ),
    ]
