# Generated by Django 2.2.6 on 2019-11-23 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20191122_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 2, 54, 59, 730937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 2, 54, 59, 729327), verbose_name='date published'),
        ),
    ]
