# Generated by Django 2.2.6 on 2019-11-23 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20191123_0254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.DateField(default=datetime.datetime(2019, 11, 23, 9, 12, 3, 267266)),
        ),
    ]
