# Generated by Django 2.2.6 on 2019-11-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20191123_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.CharField(default='11/23/19', max_length=25),
        ),
    ]
