# Generated by Django 2.2.6 on 2019-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20191123_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.CharField(default='11/24/19', max_length=25),
        ),
    ]
