# Generated by Django 2.2.6 on 2019-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20191124_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpname', models.CharField(default=None, max_length=200)),
                ('activityname', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(default=None, max_length=25)),
                ('frname', models.CharField(default=None, max_length=25)),
                ('money', models.IntegerField()),
                ('time', models.CharField(default='11/24/19', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpname', models.CharField(default=None, max_length=200)),
                ('activityname', models.CharField(max_length=200)),
                ('username', models.CharField(default=None, max_length=25)),
                ('money_gave', models.IntegerField()),
                ('money_took', models.IntegerField()),
                ('tag', models.CharField(max_length=50)),
                ('time', models.CharField(default='11/24/19', max_length=25)),
            ],
        ),
    ]
