# Generated by Django 2.2.6 on 2019-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_grouptable_grouptrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.CharField(default='11/25/19', max_length=25),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='time',
            field=models.CharField(default='11/25/19', max_length=25),
        ),
        migrations.AlterField(
            model_name='grouptrans',
            name='time',
            field=models.CharField(default='11/25/19', max_length=25),
        ),
    ]
