# Generated by Django 2.2.6 on 2019-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20191125_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendt',
            name='time',
            field=models.CharField(default='2019-11-25', max_length=25),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='time',
            field=models.CharField(default='2019-11-25', max_length=25),
        ),
        migrations.AlterField(
            model_name='grouptrans',
            name='time',
            field=models.CharField(default='2019-11-25', max_length=25),
        ),
    ]
